#!/bin/sh

# Sass watcher
printf "Starting node-sass ... "
tmux new-session -d -s "sass"
tmux send -t sass "node-sass --watch src/sass/main.sass --output ./" ENTER
printf "done\n"

# Pug watcher
printf "Starting pug ... "
tmux new -d -s "pug"
tmux send -t pug "pug -w src/pug/index.pug -o ./" ENTER
printf "done\n"

# Server
printf "Starting lite-server ... "
tmux new -d -s "server"
tmux send -t server "lite-server" ENTER
printf "done\n"

printf "Finished\n"
